GET http://localhost:5000/products/

###
GET http://localhost:5000/products/5

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "jihan",
    "rentangHarga": "Rp. 3000 - Rp. 5000",
    "description": "ya coba aja"
}

###
PUT http://localhost:5000/products/1
Content-Type: application/json

{
    "name": "abdul rohman",
    "rentangHarga": "Rp. 3000 - Rp. 5000",
    "description": "ya coba aja lgi"
}

###
DELETE http://localhost:5000/products/5